export enum TipoPago {
    EFECTIVO = 'EFECTIVO',
    TARJETA = 'TARJETA',
    TRANSFERENCIA = 'TRANSFERENCIA',
    CHEQUE = 'CHEQUE',
    QR = 'QR',
    GIFT_CARD = 'GIFT_CARD',
    MERCADO_PAGO = 'MERCADO_PAGO',
}